In [ ]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df = pd.read_csv("dirty_cafe_sales.csv")
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Shape: (10000, 8)

Columns:
['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date']

Data Types:
Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

First 5 Rows:

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

Last 5 Rows:

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df) * 100).round(2)
missing_summary = pd.DataFrame({"Missing Values": missing_values,"Missing %": missing_percentage})

missing_summary = missing_summary.sort_values("Missing %",ascending=False)

missing_summary

                  Missing Values  Missing %
Location                    3265      32.65
Payment Method              2579      25.79
Item                         333       3.33
Price Per Unit               179       1.79
Total Spent                  173       1.73
Transaction Date             159       1.59
Quantity                     138       1.38
Transaction ID                 0       0.00

In [ ]:
invalid_values = ["ERROR", "UNKNOWN", "None", "unknown", "error", ""]

for column in df.columns:
    count = df[column].astype(str).str.strip().isin(invalid_values).sum()

    print(f"{column}: {count} invalid values")

Transaction ID: 0 invalid values
Item: 636 invalid values
Quantity: 341 invalid values
Price Per Unit: 354 invalid values
Total Spent: 329 invalid values
Payment Method: 599 invalid values
Location: 696 invalid values
Transaction Date: 301 invalid values

In [ ]:
print("Number of duplicated rows:", df.duplicated().sum())

Number of duplicated rows: 0

In [ ]:
clean_df = df.copy()

clean_df.shape

(10000, 8)

In [ ]:
clean_df.columns = (clean_df.columns.str.strip().str.lower().str.replace(" ", "_"))

clean_df.columns

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='object')

In [ ]:
invalid_values = ["ERROR","UNKNOWN","None","unknown","error",""]

clean_df = clean_df.replace(invalid_values, np.nan)

clean_df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
text_columns = ["item","payment_method","location"]

for column in text_columns:
    clean_df[column] = (clean_df[column].astype("string").str.strip())

In [ ]:
numeric_columns = ["quantity","price_per_unit","total_spent"]

for column in numeric_columns:
    clean_df[column] = pd.to_numeric(clean_df[column],errors="coerce")

clean_df[numeric_columns].dtypes

quantity          float64
price_per_unit    float64
total_spent       float64
dtype: object

In [ ]:
clean_df["transaction_date"] = pd.to_datetime(clean_df["transaction_date"],errors="coerce")

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   string
 2   quantity          9521 non-null   float64
 3   price_per_unit    9467 non-null   float64
 4   total_spent       9498 non-null   float64
 5   payment_method    6822 non-null   string
 6   location          6039 non-null   string
 7   transaction_date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(1), string(3)
memory usage: 625.1+ KB

In [ ]:
clean_df.isnull().sum()

transaction_id         0
item                 969
quantity             479
price_per_unit       533
total_spent          502
payment_method      3178
location            3961
transaction_date     460
dtype: int64

In [ ]:
payment_mode = clean_df["payment_method"].mode()[0]

clean_df["payment_method"] = (clean_df["payment_method"].fillna(payment_mode))

print("Payment Method mode:", payment_mode)

Payment Method mode: Digital Wallet

In [ ]:
location_mode = clean_df["location"].mode()[0]

clean_df["location"] = (clean_df["location"].fillna(location_mode))

print("Location mode:", location_mode)

Location mode: Takeaway

In [ ]:
clean_df.loc[
    clean_df["quantity"].isna() & clean_df["total_spent"].notna() & clean_df["price_per_unit"].notna(),"quantity",
] = (
    clean_df["total_spent"] / clean_df["price_per_unit"]
)

clean_df["quantity"] = clean_df["quantity"].round().astype(int)

In [ ]:
clean_df.loc[
    clean_df["total_spent"].isna()
    & clean_df["quantity"].notna()
    & clean_df["price_per_unit"].notna(),
    "total_spent",
] = (
    clean_df["quantity"] * clean_df["price_per_unit"]
)

In [ ]:
clean_df.loc[
    clean_df["price_per_unit"].isna()
    & clean_df["total_spent"].notna()
    & clean_df["quantity"].notna(),
    "price_per_unit",
] = (
    clean_df["total_spent"] / clean_df["quantity"]
)

In [ ]:
price_to_item = {
    1.0: "Cookie",
    1.5: "Tea",
    2.0: "Coffee",
    5.0: "Salad",
  }

clean_df.loc[
    clean_df["item"].isna()
    & clean_df["price_per_unit"].isin(price_to_item.keys()),
    "item",
] = clean_df.loc[
    clean_df["item"].isna()
    & clean_df["price_per_unit"].isin(price_to_item.keys()),
    "price_per_unit",
].map(
    price_to_item
)

In [ ]:
missing_dates = clean_df["transaction_date"].isnull().sum()

print("Missing transaction dates:", missing_dates)

Missing transaction dates: 460

In [ ]:
clean_df = clean_df.dropna(subset=["transaction_date"])

In [ ]:
print("\nRemaining Missing Values:")
print(clean_df.isnull().sum())

print("\nRemaining Duplicates:")
print(clean_df.duplicated().sum())

Remaining Missing Values:
transaction_id       0
item                 0
quantity             0
price_per_unit      19
total_spent         19
payment_method       0
location             0
transaction_date     0
dtype: int64

Remaining Duplicates:
0

In [ ]:
clean_df = clean_df.dropna(subset=['price_per_unit', 'total_spent'])

In [ ]:
clean_df["revenue"] = (clean_df["quantity"] * clean_df["price_per_unit"])

clean_df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,revenue,average_transaction_value
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,4.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,12.0,12.0
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,4.0
3,TXN_7034554,Salad,2,5.0,10.0,Digital Wallet,Takeaway,2023-04-27,10.0,10.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,4.0

In [ ]:
avg_transaction = clean_df["revenue"].mean()
print("Average Transaction Value:", avg_transaction.round(2))

Average Transaction Value: 8.93

In [ ]:
total_transactions = clean_df["transaction_id"].nunique()

total_quantity = clean_df["quantity"].sum()

total_revenue = clean_df["revenue"].sum()

average_transaction = clean_df["revenue"].mean()

average_unit_price = clean_df["price_per_unit"].mean()

print("Total Transactions:", total_transactions)
print("Total Quantity Sold:", total_quantity)
print("Total Revenue:", round(total_revenue, 2))
print("Average Transaction Value:", round(average_transaction, 2))
print("Average Unit Price:", round(average_unit_price, 2))

Total Transactions: 9521
Total Quantity Sold: 28793
Total Revenue: 84984.5
Average Transaction Value: 8.93
Average Unit Price: 2.95

In [ ]:
item_sales = (clean_df.groupby("item").agg(
        transactions=("transaction_id", "nunique"),
        quantity_sold=("quantity", "sum"),
        revenue=("revenue", "sum")
    ) .sort_values("revenue", ascending=False))

item_sales

          transactions  quantity_sold  revenue
item
Juice             2047           6129  18198.0
Salad             1098           3309  16535.0
Sandwich          1071           3253  13020.0
Smoothie          1046           3204  12816.0
Cake              1081           3275   9816.0
Coffee            1122           3420   6838.0
Tea               1024           3119   4681.5
Cookie            1032           3084   3080.0

In [ ]:

clean_df["year"] = clean_df["transaction_date"].dt.year
clean_df["month"] = clean_df["transaction_date"].dt.month
clean_df["month_name"] = clean_df["transaction_date"].dt.month_name()

In [ ]:
monthly_sales = (
    clean_df
    .groupby(["year", "month", "month_name"])
    .agg(
        transactions=("transaction_id", "nunique"),
        revenue=("revenue", "sum")
    )
    .reset_index()
    .sort_values(["year", "month"])
)

monthly_sales

    year  month month_name  transactions  revenue
0   2023      1    January           817   7291.0
1   2023      2   February           724   6614.5
2   2023      3      March           826   7246.0
3   2023      4      April           772   7206.5
4   2023      5        May           775   6978.0
5   2023      6       June           817   7365.5
6   2023      7       July           791   6908.5
7   2023      8     August           801   7043.5
8   2023      9  September           786   6855.0
9   2023     10    October           837   7300.0
10  2023     11   November           782   6983.5
11  2023     12   December           793   7192.5

In [ ]:
fig = px.bar(
    item_sales.reset_index(),
    x="item",
    y="revenue",
    title="Revenue by Item",
    labels={
        "item": "Item",
        "revenue": "Revenue"
    },
    text_auto=".2s"
)

fig.update_layout(
    xaxis_title="Item",
    yaxis_title="Revenue",
    template="plotly_white"
)

fig.show()

In [ ]:
fig = px.bar(
    item_sales.sort_values(by="quantity_sold", ascending=False).reset_index(),
    x="item",
    y="quantity_sold",
    title="Quantity Sold by Item",
    labels={
        "item": "Item",
        "quantity_sold": "Quantity Sold"
    },
    text_auto=".2s"
)

fig.update_layout(
    xaxis_title="Item",
    yaxis_title="Quantity Sold",
    template="plotly_white"
)

fig.show()

In [ ]:
fig = px.line(
    monthly_sales,
    x="month_name",
    y="revenue",
    markers=True,
    title="Monthly Revenue Trend"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue",
    template="plotly_white"
)

fig.show()

In [ ]:
clean_df.to_csv(
    "dirty_cafe_sales_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.